# Generated by Django 5.1.1 on 2024-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Страна"
            ),
        ),
    ]
