# Generated by Django 5.1.1 on 2024-09-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение статьи.",
                null=True,
                upload_to="media/",
                verbose_name="Изображение",
            ),
        ),
    ]
