# Generated by Django 5.1.1 on 2024-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "created_at", "updated_at", "category"],
                "permissions": [("set_published", "Can publish posts")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
