# Generated by Django 5.1.1 on 2024-09-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "created_at", "updated_at", "category"],
                "permissions": [
                    ("set_published", "Can publish products"),
                    ("edit_published", "Can edit products"),
                    ("edit_category", "Can edit categories"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
